### ISSUE TITLE
Usage with Nuxt.js

### ISSUE THREAD

**Issue by michaelcpuckett** [berniegp/vue-unique-id#1]
Doesn't seem to maintain IDs with Nuxt.. I wonder if it would work if it were somehow in the Vuex store.

**Comment by berniegp** [comment]
I don't use Nuxt but it looks like it's based on vue.js so I would expect this plugin to work. What's the actual problem you're facing and expected behavior?

If you provide a reproducible demo of the problem (jsfiddle for example) I can have a look.
