### ISSUE TITLE
Error when used in typescript program

### ISSUE THREAD

**Issue by badders** [berniegp/vue-unique-id#2]
I have a ts project created with vue-cli, and have addedf vue-unique-id. I have component in my template equivalent to `<div id="uid">` and In my mounted method i do

`const component = document.getElementById(this.uid.toString());`

However i get a compiler error of 
Property 'uid' does not exist on type 'ComponentName'.

Everything seems to work correctly in the browser, but it would be nice to be able to get rid of this message

**Comment by berniegp** [comment]
Disclaimer: I don't use typescript myself so this might be wrong.

Perhaps this will help
- https://github.com/vuejs/vue/issues/8954
- https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins
- https://stackoverflow.com/questions/50909703/augmenting-vue-js-in-typescript
- https://www.mistergoodcat.com/post/vuejs-plugins-with-typescript

Try adding a file like this in your project (e.g. `vue-unique-id.d.ts`)
```
// 1. Make sure to import 'vue' before declaring augmented types
import Vue from 'vue'

// 2. Specify a file with the types you want to augment
//    Vue has the constructor type in types/vue.d.ts
declare module 'vue/types/vue' {
  // 3. Declare augmentation for Vue
  interface Vue {
    uid: string;
    $id(id?: string):  string;
    $idRef(id?: string): string;
  }
}
```

Let me know if that works for you.

**Comment by badders** [comment]
Yep sorted it thanks, new to typescript so I wasnt familiar with that

**Comment by berniegp** [comment]
Did you have to modify what I suggested or did you use it as-is? Just in case I or someone else needs it later :)

**Comment by berniegp** [comment]
@badders The TypeScript declaration files are now bundled with the package since v1.1.1 so what you did is no longer necessary.
