### ISSUE TITLE
TypeError: Cannot redefine property: uid

### ISSUE THREAD

**Issue by thechrisoshow** [berniegp/vue-unique-id#4]
Hi,

Just updated to Vue 3.1.2, and we're now getting the following error:

`TypeError: Cannot redefine property: uid`

I think this might be because the library is creating a uid field on the component to store the update.

**Comment by berniegp** [comment]
Hello,

I can't see any Vue 3.x version on https://github.com/vuejs/vue/releases. In fact Vue 3, as far as I can see, has not been released yet! Which version are you referring to exactly?

**Comment by thechrisoshow** [comment]
Doh! I'm an eejit - I meant 2.6.11 (I was looking in my yarn.lock and was looking at vuex)

**Comment by berniegp** [comment]
That makes more sense!

However I use 2.6.11 myself (and test with that version) without any issues. Do you have any other Vue plugins in your setup? I suspect another one is defining the `uid` property.

**Comment by berniegp** [comment]
@thechrisoshow did you figure it out?

**Comment by thechrisoshow** [comment]
No I didn't sorry - however when I removed the vue-unique-id library the error went away. (I ended up rolling my own unique id generator in the end). Thanks anyway Bernie

**Comment by berniegp** [comment]
@thechrisoshow and anyone else facing a similar issue: since v3.1.0 it's now possible to change the `uid` property name with the plugin options.
